# Ordfanger Telegram Bot deployment configuration

service: ordfanger-telegram-bot
frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  stage: STAGE
  stackName: ordfanger-telegram-bot-stack
  apiName: ordfanger-telegram-bot
  region: eu-central-1
  profile: SERVERLESS_USER
  memorySize: 128
  timeout: 5
  deploymentBucket:
    name:  ordfanger.${self:provider.region}.deploys
  deploymentPrefix: ordfanger-telegram-bot
  versionFunctions: false
  environment:
    TABLE_NAME: ${opt:stage, self:provider.stage}-words
    BOT_API_KEY: ${ssm:BOT_API_KEY}
  iamRoleStatements:
   - Effect: Allow
     Action:
       - dynamodb:DescribeTable
       - dynamodb:Query
       - dynamodb:Scan
       - dynamodb:GetItem
       - dynamodb:PutItem
       - dynamodb:UpdateItem
       - dynamodb:DeleteItem
     Resource: "arn:aws:dynamodb:*:*:*"

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  server:
    handler: bin/server
    name: ${self:provider.stage}-${self:provider.apiName}-server
    events:
      - http:
          path: bot-updates
          method: post

resources:
  Resources:
   WordsDynamoDbTable:
     Type: 'AWS::DynamoDB::Table'
     DeletionPolicy: Retain
     Properties:
       AttributeDefinitions:
         - AttributeName: word
           AttributeType: S
       KeySchema:
         - AttributeName: word
           KeyType: HASH
       ProvisionedThroughput:
         ReadCapacityUnits: 1
         WriteCapacityUnits: 1
       TableName: '${opt:stage, self:provider.stage}-words'