version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run:
          name: Installing Serverless CLI
          command: |
            curl -sL https://deb.nodesource.com/setup_11.x | sudo -E bash -
            sudo apt-get install -y nodejs
            sudo npm i -g serverless
      - run:
          name: Make (installing golang modules)
          command: make
      - save_cache:
          key: v1-pkg-cache
          paths:
            - /go/pkg
      - run:
          name: Deploy lambda
          command: make deploy-server