version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
#    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run:
          name: Installing Serverless CLI
          command: sudo npm i -g serverless
      - run:
          name: Make (installing golang modules)
          command: make
      - save_cache:
          key: v1-pkg-cache
          paths:
            - /go/pkg
      - run:
          name: Deploy lambda
          command: make deploy-server